### ISSUE TITLE
PDX, Spring 2018

### ISSUE THREAD

**Issue by danielbachhuber** [maintainerati/events#97]
A placeholder issue for planning [Maintainerati Portland](https://maintainerati.org/), Spring 2018.

Logistics:

* [ ] Find a venue.
* [ ] Pick a date.
* [ ] Update the website to include event details.
* [ ] Promote among local groups.

**Comment by danielbachhuber** [comment]
@mbbroberg How's the venue search coming along?

**Comment by mbbroberg** [comment]
Having less luck finding one than I expected pinged Puppet and following up
tonight. Realized I no longer know people at New Relic. This ones a little
harder than I thought so i could use a hand to get this one nailed down.
Thanks!

**Comment by mbbroberg** [comment]
Confirmed that Puppet only allows events after 5:30pm during the week. @danielbachhuber, officially asking we both hunt for places. 

Hey @nayafia and @MikeMcQuaid, if there's some (reasonable) cost for a venue, would you be able to help? That will broaden the search quite a bit.

**Comment by danielbachhuber** [comment]
I've asked a few people and will let you know what I hear.

I wonder if Treehouse would host something like this?

Alternatively, if we're open to outside downtown PDX, I think a number of options open up: common space in libraries, fire stations, etc.

**Comment by MikeMcQuaid** [comment]
> Hey @nayafia and @MikeMcQuaid, if there's some (reasonable) cost for a venue, would you be able to help? That will broaden the search quite a bit.

@mbbroberg Yep! Let us know where you're thinking and how much and we'll confirm first.

**Comment by danielbachhuber** [comment]
Umpqua Bank at Fox Tower has a community conference room anyone can reserve for free.

There are 8 chairs around the table, and the guy said they've had up to 15 people in the room before (although it can get stuffy pretty quick if we close the door).

For the last week in April, they have every day except Thursday available right now.

**Comment by mbbroberg** [comment]
Got in touch with the lead at New Relic and they're a 👎 as well for full days. 

> There are 8 chairs around the table

I'm down to try it, though I bet we'd get closer to 20-30 attendees if we do this. Maybe we can hunt down something multi-room. 

Picking a friend's brain who knows people around Portland today. 🤞

**Comment by danielbachhuber** [comment]
I've [posted an ask in PDX Switchboard too](https://pdxstartups.switchboardhq.com/posts/34835-looking-for-free-or-reasonably-priced-space-for-open-source-event).

**Comment by danielbachhuber** [comment]
I've also called [Norse Hall](http://www.norsehall.org/facility/) about their Oslo Room, which can take up to 50.

**Comment by danielbachhuber** [comment]
Norse Hall has two rooms available on Wednesday, April 25th and Thursday, April 26th:

* Oslo Lounge, seats up to 50, $635
* Nordic Room, seats up to 70, $495

Both include use of tables, chairs, power outlets/wifi, and cleanup.

I told the organizer we'd get back to him in the next week.

**Comment by nayafia** [comment]
Yep, that's fine for us to sponsor!

**Comment by mbbroberg** [comment]
@danielbachhuber awesome news! I did a little digging [on their site](http://www.norsehall.org/facility/) and think the Nordic room looks ready for breakout sessions right away. I'd love for us to meet up in the Library to start the day if it's available (similar to what we did in SF, then went to breakout room). Once confirmed, I'm happy to help on the website update or other next steps. 

Also, this: 

> At night, the glow from Norse Hall’s vintage neon sign provides the room with its signature romance, making it a favorite space for Argentine tango dancers. 

😄

**Comment by danielbachhuber** [comment]
This was the latest from Saturday:

> I put a soft hold on the [Nordic] room for April 25th, meaning no one else will rent it without your first refusal. I should be able to confirm by Tuesday that no one else already has it reserved for a Lodge event. I'm out of town this weekend, and will contact you then.

**Comment by mbbroberg** [comment]
YES! That's so exciting. Think it's solid enough to get on the website @danielbachhuber? I'm happy to work with @nayafia or @MikeMcQuaid on that next 😄

**Comment by danielbachhuber** [comment]
At the very least, we could have a "Coming This Spring" with email capture form until all of the details are finalized.

Before we publicize too much, I'd like to pick a subtopic for our event so it has a little bit of focus. As a suggestion, I'm really interested in the application of open source in the real world (e.g. healthcare, urban development, etc.), so I was thinking it might be interesting to invite some people in that space.

@nayafia @MikeMcQuaid Unless you have preferences otherwise, I can pay for event costs on my own and then submit an invoice for reimbursement.

**Comment by danielbachhuber** [comment]
> Unless you have preferences otherwise, I can pay for event costs on my own and then submit an invoice for reimbursement.

On second thought... the venue requires event insurance, which I'm not sure I'm comfortable taking out in my own name. Is it possible for GitHub to take this on directly?

**Comment by Lieke22** [comment]
@danielbachhuber Hi Daniel, nice to meet you! I'll be repping from GitHub side now :) 

You can also ask the venue to send us an invoice directly (invoices@github.com) and please cc me (lieke22@github.com).

Let me know if that works 👍

**Comment by mbbroberg** [comment]
You rock @Lieke22!

**Comment by danielbachhuber** [comment]
The Nordic Hall didn't work out because of liability insurance issues. We're back to square one: needing to find a venue.

**Comment by danielbachhuber** [comment]
Closing as `maybelater`. I'm not personally motivated enough to make this happen now.

**Comment by mbbroberg** [comment]
I feel you @danielbachhuber. It was fun to try -- let's circle back to this when the opportunity comes around.

**Comment by danielbachhuber** [comment]
👍 Sounds good.
